### PR TITLE
Try build pogo with java 11

### PR DESCRIPTION
**Pull request by dlacoste-esrf**
Working build with java 11

### CODE REVIEW

**Comment by Pascal-Verdier** [comment]
Seems working fine with java 11 and 13

**Comment by Pascal-Verdier** [comment]
Question:
Do we impose to all Pogo users to use java 11 or higher, or wait a bit ?

**Comment by andygotz** [comment]
This solves a long standing issue - well done to @dlacoste-esrf for solving this!

I would provide the version for Java 11 and ask users to test it. The previous versions for Java 8 will still be available in case of issues.

**Comment by t-b** [comment]
So the next version of pogo is java11 only? That would actually help in the tango source distribution as we don't have to support multiple java versions.

**Pull request merged**
