### PR TITLE
Mavenization2

### PR DESCRIPTION
**Pull request by Ingvord**
@Pascal-Verdier hi, I have managed to mavenize pogo! Could you please review this PR:

First pull the latest changes in the branch

```
$> git pull
$> git checkout Mavenization2
```

Then try to open the project in IDEA, build and run pogo as described in [this Wiki page](https://github.com/tango-controls/pogo/wiki/home)

Once you confirm that this is fine I will squash and merge this PR

### CODE REVIEW

**Comment by Pascal-Verdier** [comment]
Hi Igor

I cloned pogo.
I did    **git checkout Mavenization2**
I tried to start eclipse, but it cannot load the project.
Is it normal ?

I did    **cd org.tango.pogo.pogo_gui**  (correct ?)
mvn package
and the result was:
**[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pogo 9.4.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for fr.esrf.tango.pogo:fr.esrf.tango.pogo:jar:9.4.6-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for fr.esrf.tango.generator.xtend:fr.esrf.tango.generator.xtend:jar:9.4.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.838 s
[INFO] Finished at: 2017-08-04T09:18:10+02:00
[INFO] Final Memory: 17M/966M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Pogo: Could not resolve dependencies for project org.tango.tools.pogo.gui:Pogo:jar:9.4.6-SNAPSHOT: The following artifacts could not be resolved: fr.esrf.tango.pogo:fr.esrf.tango.pogo:jar:9.4.6-SNAPSHOT, fr.esrf.tango.generator.xtend:fr.esrf.tango.generator.xtend:jar:9.4.6-SNAPSHOT: Failure to find fr.esrf.tango.pogo:fr.esrf.tango.pogo:jar:9.4.6-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public-jboss was cached in the local repository, resolution will not be reattempted until the update interval of JBoss has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException**

**Comment by Ingvord** [comment]
Hi, I have not tried to use pogo in eclipse, I use IDEA instead. Could you please try with IDEA?

**Comment by Pascal-Verdier** [comment]
Hi Again
It works with maven and with IDEA.

BUT:
1) I think for Pogo we need a fat jar (for XTend, XText, eclipse, .... libs)
2) To add a new feature in Pogo, we change the **fr/esrf/tango/pogo/PogoDsl.xtext** file and then we need to run the  **fr/esrf/tango/pogo/GeneratePogoDsl.mwe2** file.
   It is necessary to generate file under **fr/esrf/tango/pogo/pogoDsl/** 
   I do not know how to do it with IDEA (????)

**Comment by Ingvord** [comment]
@Pascal-Verdier thanks for your feedback. 

> I think for Pogo we need a fat jar (for XTend, XText, eclipse, .... libs)

Done in b36ca32

Run `mvn package` the fat jar is `{POGO_ROOT}/org.tango.pogo.pogo_gui/target/Pogo-9.4.6-SNAPSHOT-jar-with-dependencies.jar`

> To add a new feature in Pogo, we change the meta model in fr/esrf/tango/pogo/PogoDsl.xtext file and then we need to run the fr/esrf/tango/pogo/GeneratePogoDsl.mwe2 file.
It is necessary to generate files under fr/esrf/tango/pogo/pogoDsl/
I do not know how to do it with IDEA (????)

This is now done automatically each time mvn builds the project. So just do the changes and then `mvn clean package`

If you want to build only one module i.e. fr.esrf.tango.pogo instead of all every time, you can run `mvn package -pl ../fr.esrf.tango.pogo -am`. This will build only one module. More info [here](https://stackoverflow.com/questions/1114026/maven-modules-building-a-single-specific-module)

__NOTE__ all maven commands must be run in fr.esrf.tango.pogo.parent folder

**Comment by Pascal-Verdier** [comment]
About fr/esrf/tango/pogo/PogoDsl.xtext file , it seems OK.
About fat jar, I started build at 13:00 and now (14:40) it is not finished......

I have several warnings like
**[WARNING] repository metadata for: 'artifact org.eclipse.xtext:org.eclipse.xtext.generator' could not be retrieved from repository: central due to an error: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out)**

**Comment by Ingvord** [comment]
@Pascal-Verdier looks like there is network configuration problem. Are you sure you set up proxy correctly?

**Comment by Pascal-Verdier** [comment]
Hi 
Fat jar needs 4h 30 to be built....
I think, if my proxy was badly configured, the problem  was the same to compile (when update maven cache) or for other jar generation.

**Comment by Pascal-Verdier** [comment]
OK
Proxy was well defined for http and https in environment.
Well defined for http in .m2/settings.xml.
but not defined for https in  .m2/settings.xml.   :)
Now it works fine.
You can merge and generate a 9.5.0 jar file.
PS:
The jar file was like : **org.tango.pogo-9.x.x.jar**
could we keep this name to do not have to modify all script files ?

**Comment by Pascal-Verdier** [comment]
Hi again
How to remove all DEBUG  traces created with this new release ?

**Comment by Ingvord** [comment]
>  The jar file was like : org.tango.pogo-9.x.x.jar
could we keep this name to do not have to modify all script files ?

I have changed maven assembly so it now generates only fat jar (without -jar-with-dependencies). Concerning the version - it just takes the version from parent/pom.xml. This can be changed manually (do not forget to change version in every project then). Usually it is done by maven-release-plugin but it does not work for pogo, because of the non-trivial project structure (due to xtex). I will try to fix this in the future.

> How to remove all DEBUG traces created with this new release ?

I have added logback.xml to _generator_ module. It seems better now.

**Comment by Ingvord** [comment]
Unfortunately I can not setup maven-release-plugin due to forced project structure (forced by xtext plugin). Maven requires root pom.xml to be present but executing xtext plugin from the root folder fails. Maybe someone brave enough could resolve this in the future. Here is the related SO discussion: [link](https://stackoverflow.com/questions/12295462/how-to-configure-scm-in-flat-multi-module-projects-in-maven)

Anyway currently you can follow this simple instruction: [link](https://github.com/tango-controls/pogo/wiki#release-pogo-using-maven) to release Pogo manually,

**Pull request merged**
